####################
# Workshop Admin
####################

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-administrator
  namespace: default
rules:
- apiGroups: ["", "extensions", "apps", "batch", "rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: workshop-administrator
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: workshop-administrator-binding
  namespace: default
roleRef:
  kind: Role
  name: workshop-administrator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: workshop-administrator
  namespace: default

####################
# Workshop viewer
####################

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: workshop-viewer
  namespace: default
rules:
- apiGroups: ["", "extensions", "apps", "batch"]
  resources: ["*"]
  verbs: ["get", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workshop-viewer
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: workshop-viewer-binding
  namespace: default
roleRef:
  kind: Role
  name: workshop-viewer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: workshop-viewer
  namespace: default