version: '3'
services:
  app:
    build: .
    ports:
    - "8080:8080"
    links:
    - redis
    environment:
      MESSAGE: 'yoyo" wwsas'
      REDIS_URL: redis://redis:6379
  redis:
    image: redis
