version: '3'
services:
  app:
    build: .
    # image: netlight/kubernetes-workshop-example-app
    ports:
    - "8080:8080"
    links:
    - redis
    environment:
      MESSAGE: Hello World!
      REDIS_URL: redis://redis:6379
  redis:
    image: redis
