apiVersion: v1
kind: Service
metadata:
  name: {{PLACEHOLDER}}
  labels:
    app: {{PLACEHOLDER}}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{PLACEHOLDER}}
