apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-kubernetes
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hello.eks-workshop.edge-labs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-kubernetes
          servicePort: http