apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{PLACEHOLDER}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{PLACEHOLDER}}.eks-workshop.edge-labs.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{PLACEHOLDER}}
          servicePort: http