apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-app-redis
spec:
  serviceName: my-app-redis
  replicas: 1
  selector:
    matchLabels:
      app: my-app-redis
  template:
    metadata:
      labels:
        app: my-app-redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
          name: redis
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /data
      volumes:
      - name: workdir
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-redis
  labels:
    app: my-app-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      name: redis
  selector:
    app: my-app-redis
